@extends('layouts.app1')
@section('navber')
  @include('inc.nav')
@endsection
@section('loginmodel')
  @include('inc.log_reg')
@endsection
@section('slogan')
  @include('inc.slogan')
@endsection
@section('content')
  @include('inc.home_cat')
@endsection
@section('footer')
  @include('inc_in.das.footer')
@endsection
