@extends('layouts.app1')
@section('navber')
  @include('inc.nav')
@endsection
@section('loginmodel')
  @include('inc.log_reg')
@endsection
@section('slogan')
  @include('inc.slogan')
@endsection
@section('content')
  @include('inc.product_dis')
@endsection
@section('divider')
  @include('inc.homediv')
@endsection
  @section('product')
    @include('inc.cat')
  @endsection
@section('footer')
  @include('inc.footer')
@endsection
